### ISSUE TITLE
Apostrophes in layer's name cause failure using openlayers

### ISSUE THREAD

**Issue by marcbeldata** [qgis2web/qgis2web#1022]
macOS version: Ventura 13.2 (ARM)
QGIS version: 3.22.16 (LTR)
qgis2web plugin version: 3.16.0

Using the OpenLayers option, if one of the layers has a name with an apostrophe ( ' , as in "d'exemple"), qgis2web doesn't generate any preview, and the export is empty (any layer exported). 

Selecting Leaflet, there is no issue: preview and export files are generated, including those with an apostrophe.

With OpenLayers, when deselecting the layer with the apostrophe, the rest of the layers are then previewed and exported.

**Comment by andreaordonselli** [comment]
This happens because the `title` field of the layers.js file is among these `' '` rather than among these `" "`

navigate to path C:\Users\User\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis2web\

save a copy of the olLayerScripts.py file somewhere, then edit in these lines by replacing `'` with `"` and in the img source backwards `"` with `'`, like this:

line 412
` title: "<img src='styles/legend/%(icon)s.png' /> %(name)s"`
line 421
` title: "%(name)s"`
line 431
` <img src='styles/legend/%(icon)s_%(count)s.png' /> %(text)s<br />`
line 434
` title: "%(name)s<br />%(icons)s"`

Restart qgis and try to export again.
We have changed only the vector export in JSON, if you want to use the apostrophe in the name of other layers such as wms, wfs, raster, xyz etc... you have to make the same change in other sections of the file
It should work, let me know

**Comment by andreaordonselli** [comment]
Released version [3.17.3](https://github.com/qgis2web/qgis2web/releases/tag/v3.17.3) which includes a fix for this issue. The update will be available soon from the QGIS plugin repository. Thanks for the tip. Please consider a small donation to support qgis2web via the button on the home page. Thank you.
