### ISSUE TITLE
legend for renderer invertedPolygonRenderer not supported

### ISSUE THREAD

**Issue by kraln** [qgis2web/qgis2web#1034]
When trying to export a project with an invertedPolygonRenderer, all hell breaks loose:

Openlayers will export, but half-finished and broken
Leaflet and MapboxGL exporter crash. 

Issue (for leaflet, at least) is around line 363 of leafletLayerScripts, the code does not handle the "else" path where classes is not set, assumes there is classes, and then tries to enumerate them (and references the zero index). I haven't looked but assume the problem is the same for the MapboxGL exporter.

**Comment by andreaordonselli** [comment]
You forgot to put the shp in the zip

**Comment by andreaordonselli** [comment]
Even without your data, I have verified that it is very complicated for any webgis to execute the "inverted polygon" style. In fact, qgis2web exports do not export a result because they do not export a style, i.e. the geometries are in the map, but they cannot be seen because the system fails to color them.
I don't see any other method than to act on the geometries by drawing the graphic shape reversed with respect to the current one, and applying a standard "fill" style to it.
