### ISSUE TITLE
The export contains malware

### ISSUE THREAD

**Issue by DCCP80** [qgis2web/qgis2web#1059]
I checked and didn't see any issues about this, and there is no tab for security. I am using this for a client and they can't download the zipped archive of this because of the malware, i've attached an image from windows defender. 
![qgis2web_threat](https://github.com/qgis2web/qgis2web/assets/50685835/287cae97-10dd-4884-8200-730eb95d6a86)

This is a major issue please respond ASAP.

Thank you,
Dan Amrine

**Comment by andreaordonselli** [comment]
This is the first time I've seen this problem. I do not know how to help you. Have you changed the program in any way?

**Comment by riccardoklinger** [comment]
Hi Dan,I do understand the urgency for you as a “freelancer” or contractor. Demanding something to be finished with the word ASAP is probably not the best as we work on qgis in our free time and most of us do not get any compensation for doing so.Best, RiccardoVon meinem iPhone gesendetAm 10.04.2024 um 17:21 schrieb Daniel Amrine ***@***.***>:﻿
I checked and didn't see any issues about this, and there is no tab for security. I am using this for a client and they can't download the zipped archive of this because of the malware, i've attached an image from windows defender.
qgis2web_threat.JPG (view on web)
This is a major issue please respond ASAP.
Thank you,
Dan Amrine

**Comment by DCCP80** [comment]
> Hi Dan,I do understand the urgency for you as a “freelancer” or contractor. Demanding something to be finished with the word ASAP is probably not the best as we work on qgis in our free time and most of us do not get any compensation for doing so.Best, RiccardoVon meinem iPhone gesendetAm 10.04.2024 um 17:21 schrieb Daniel Amrine ***@***.***>:﻿ I checked and didn't see any issues about this, and there is no tab for security. I am using this for a client and they can't download the zipped archive of this because of the malware, i've attached an image from windows defender. qgis2web_threat.JPG (view on web) This is a major issue please respond ASAP. Thank you, Dan Amrine —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I'm so sorry, I understand this comes with using open source. I was frustrated. Please forgive using ASAP. I went through the steps and exported my active QGIS map, It works on my machine, and when i did quck scans, it was clear. However gmail wouldn't let me attach the .zip file and then my client couldn't couldn't download it from drive either. I will test the process again. I don't understand this. I'm new to hosting leaflet online, i'm still working on getting a server i can hsot from, but this is a learning process and this plugin makes it so much faster. I don't understand how this Malware could be part of the export.

**Comment by andreaordonselli** [comment]
![image](https://github.com/qgis2web/qgis2web/assets/89784373/db462f1c-21f0-4422-84f5-731b129c8852)

I can open your exported map without problems and without warnings from the windows antivirus.
Could it be that the person trying to open it has a PC on a company network with more restrictive policies than virus blocking?

PS: gmail blocks the zip because it contains javascript files, potentially executable. You need to upload the zip to a web location, maybe google drive, onedrive, dropbox and then provide the download link to third parties.

**Comment by DCCP80** [comment]
> I can open your exported map without problems and without warnings from the windows antivirus. Could it be that the person trying to open it has a PC on a company network with more restrictive policies than virus blocking?
> 
> PS: gmail blocks the zip because it contains javascript files, potentially executable. You need to upload the zip to a web location, maybe google drive, onedrive, dropbox and then provide the download link to third parties.

Thank you!  i will let my client know. I tried creating a folder in dropbox and sharing that instead of zipping it into one archive. I will let you know if that works.  again, I appreciate the help.
