### ISSUE TITLE
Diagrams are not supported by qgis2web

### ISSUE THREAD

**Issue by rymaroumane** [qgis2web/qgis2web#1074]
Hello, I'm encountering an issue while exporting my map with qgis2web. I'm unsure if this bug has already been reported; if it has I apologize for any redundancy. 
My concern lies with a specific layer where i've added diagrams, yet it seems qgis2web does not support this feature. 
Additionnally, i've noticed that color gardient categorization isn't supported either.
I really want to know where the issue comes from.
Thank you in advance for any assistance. 
![CaptQgisEmploi](https://github.com/qgis2web/qgis2web/assets/171589977/43ce681d-b02f-4d69-9356-e8c279d8c62a)

**Comment by rymaroumane** [comment]
Thank you for your prompt response.
The purpose of the diagrams in my QGIS project is to visually represent the number of job seekers in 2023 for each municipality. I created these diagrams by using text diagrams, which display the exact number of job seekers directly on the map.

I understand that qgis2web may not support complex features like these diagrams directly. Could you provide more details on how to transform these diagrams into a simple element, vector, and label as you suggested?

Additionally, here is a zip file containing my QGIS project: 
[carte tizi ouzou.zip](https://github.com/user-attachments/files/15562607/carte.tizi.ouzou.zip)

I am also curious to know if there are any plans to support these features (diagrams and color gradient categorization) in future updates of qgis2web. Is there anyone currently working on implementing these functionalities?

Thank you again for your assistance.

**Comment by andreaordonselli** [comment]
Premise: I don't understand why this layer has brown symbolism but is represented in a transparent green map
![image](https://github.com/qgis2web/qgis2web/assets/89784373/dc50e95b-0574-458a-a9b1-5358bdc4e13b)

This symbology is not supported, it needs to be simplified:
![image](https://github.com/qgis2web/qgis2web/assets/89784373/52de8764-1738-4036-a5e8-ea84bc94ea56)

I can't test this layers because I don't have the SVG icon:
![image](https://github.com/qgis2web/qgis2web/assets/89784373/ee3e9108-2708-47be-b727-9a154dd88aac)
![image](https://github.com/qgis2web/qgis2web/assets/89784373/3137d8fd-6c05-4e2e-8fbd-9f5ef9290572)

This layer contains too many features, it misleads the system, it needs to be simplified in some way:
![image](https://github.com/qgis2web/qgis2web/assets/89784373/4d2a2d05-b9e0-47ff-8c9d-170356515799)

Once the problems have been eliminated, the system is produced without too many problems, here it is in the two versions:
[leaflet.zip](https://github.com/user-attachments/files/15576606/leaflet.zip)
[openlayers - no highlight on hover.zip](https://github.com/user-attachments/files/15576633/openlayers.-.no.highlight.on.hover.zip)

Now let's get to the layer with the diagrams.
Premise: 
- diagrams are not supported for export
- data that comes from joins with other tables cannot be exported, only data stored in original layer can be exported, so after the join the original layer must be saved locally with the join data.
Conclusion:
By activating the label on the layer 
![image](https://github.com/qgis2web/qgis2web/assets/89784373/116d9888-ab2d-4676-9c8a-c4652b16fa7c)

it is possible to export the result in visual form, here is the result via the openlayers export (the leaflet export fails and at the moment I can't go into detail why)
![image](https://github.com/qgis2web/qgis2web/assets/89784373/1916ebb4-c5e2-4c51-b8ab-346afb9d739a)

Producing the web map with all the layers, this is the result:
[openlayers conclusion - no highlight on hover.zip](https://github.com/user-attachments/files/15579251/openlayers.conclusion.-.no.highlight.on.hover.zip)

You have to work on the transparencies and on what to place on top and what to place below, but the result is already good in my opinion.
That's what qgis2web, and I, can do for you.

Follow the documentation on the WIKI site https://qgis2web.github.io/qgis2web/ for more details. Graduated style is supported.

After exporting the project with qgis2web you could add the ol-ext library and do everything on this page: https://viglino.github.io/ol-ext/

I hope I've been of help to you.
Andrea.

**Comment by rymaroumane** [comment]
Thank you very much for you detailed feedback and assistance.
Symbology issues: 
1.yes I've noticed the discrepancy between the brown symbology and the transparent green representation , but I like it that way so I'm going to keep it.
2. I have simplified this symbology , but it still not supported by Leaflet ,
![image](https://github.com/qgis2web/qgis2web/assets/171589977/f7684b90-0217-4865-b053-e7063a62822c)
Same thing for the graduated style , not supported by leaflet that's unfortunate:
![image](https://github.com/qgis2web/qgis2web/assets/171589977/85b95e99-37e5-47e3-a8ea-4afe3008ce21)

Besides that, you've been very helpful, I'll carefully consider all the advice you've provided , thanks again

**Comment by andreaordonselli** [comment]
Check the supported symbologies in the WIKI.  SVG symbols only work with point layers not with polygonal layers.  One question: why do you prefer leaflet export?  for the title?  why does the pointer turn into a hand over features?  for the highlight on hover?

**Comment by rymaroumane** [comment]
OMG yes it worked, so all this time the problem was the apostrophes and I couldn't figure it out, I renamed the Fields and it immediately solved the problem, Thank you so much : 
![leaflet1](https://github.com/qgis2web/qgis2web/assets/171589977/5422f6b0-63b8-43a4-9c49-c039834f51c1)
![leaflet2](https://github.com/qgis2web/qgis2web/assets/171589977/e88e70f3-ef95-49bf-8a73-8d48d976cf24)

And to anwser your question, I prefer leaflet for all the reasons you've mentioned, especially for the highlight on hover.
Thanks again

**Comment by andreaordonselli** [comment]
An update will arrive soon that improves the visibility of svg icons in the legend. I believe that the Bovins Ovins Caprins layer, even if present in the legend, will not be shown if you turn it on.

I'm glad you solved it. I will fix openlayers to provide the same functionality. For complex projects like yours it's faster.

Please consider donating a virtual coffee via the button on the github home page to support the development of qgis2web.

Greetings.

**Comment by rymaroumane** [comment]
I'm glad to hear that you will be fixing OpenLayers to provide the same functionality, thank you for all the efforts you make to improve qgis2web.

I will definitely consider donating a virtual coffee to support the development of qgis2web. Thank you for all your hard work and support.

**Comment by andreaordonselli** [comment]
I'm glad you will support the program. With the donation you will also get qgis2opengis, I hope you will enjoy it since you have a nice project in hand.
