### ISSUE TITLE
export page is blank

### ISSUE THREAD

**Issue by LinsenHou** [qgis2web/qgis2web#1075]
I have loaded two layers in QGIS: one is an online map and the other is a layer composed of photos taken by a drone. These layers are displayed correctly in QGIS, but when I publish them using qgis2web, the second layer is not visible. I also tried publishing the second layer separately, but it appears as a blank div in web.
Pls help on this. Thanks a lot.

  - the qgis2web version: 3.36.3-Maidenhead
  - browser JS console errors :no erros
 
the layer data: https://xiaobao2.oss-cn-beijing.aliyuncs.com/geotiff/result.tif

![image](https://github.com/qgis2web/qgis2web/assets/9674322/d67dc03d-4980-496a-80c2-6e0d77fca9f5)

![image](https://github.com/qgis2web/qgis2web/assets/9674322/47f7d07c-5a67-4380-b87d-dcb6c2829e56)

**Comment by andreaordonselli** [comment]
I've run some tests with your image and actually the program fails during export. I point out that it needs to be corrected but I can't devote myself to it immediately as I'm busy with another release that will be released soon. 

**Problem:**
In any case, even if the export problem were solved, the web map would not be usable because your tif is 350mb and to be viewed on the map it would have to be downloaded locally to the user's PC every time. 
If you had more than just one image it would be even worse; keep in mind that an ideal weight for a map exported with qgis2web should be a maximum of 50mb, with this weight the user would load the map in about 20 seconds which is a long but feasible waiting time.

**Solution:** 
The best way to represent rasters in a web map is to display them as WMS. There are several websites that allow you to upload your rasters and publish them online as WMS by providing you with a link, you can upload to QGIS like any other WMS Server.
By exporting the map when the layer is turned on, the address provided will be queried and the image will arrive in the form of a mosaic, loading will be very fast. Here are some sites that provide this service for free within a certain space limit, with a fee exceeding the threshold:
- nextgis
- mygeodata cloud
- qgis cloud
