### ISSUE TITLE
Categorized simbology bug

### ISSUE THREAD

**Issue by LuBa95** [qgis2web/qgis2web#1081]
Hello there! 
I am experiencing a problem with qgis2web. I have loaded a layer with graduated symbology but the output is (as in the attached screenshot) a layer without differentiated symbology. Simply all red instead of a blue to red scale. The legend instead shows the correct gradation.
I use the most up-to-date and stable version of qgis and qgis2web, I created a new project with only this layer to ease the process and tried both Openlayers and Leaflet. 
Has anyone had similar experiences?

![graduated_style_bug](https://github.com/user-attachments/assets/d4dac874-3107-425b-9d24-7426f27c16f5)

**Comment by LuBa95** [comment]
> Graduated symbology usually works well. You can upload your qgis project.

of course, here it is
[test_webgis.zip](https://github.com/user-attachments/files/16256967/test_webgis.zip)

**Comment by andreaordonselli** [comment]
The geojson file extracted from your gpkg performs an approximation to the fifth decimal place after the decimal point, so when the webgis tries to apply the style for each variable it fails to do so because it looks for longer numbers that do not exist in the data.
Approximate your values ​​to the fifth decimal place.

Creates a new field with up to five decimal places.
![2024-07-17 08_14_19-Window](https://github.com/user-attachments/assets/0fd850d4-70ec-4a07-bbcd-796e8b726c92)

Transport your data into this new field and apply your graduated style.
![2024-07-17 08_14_43-Window](https://github.com/user-attachments/assets/838d8c14-f73b-4aa6-a279-279d886d7d0a)

Here the result
![2024-07-17 08_15_01-Window](https://github.com/user-attachments/assets/ece57f39-683e-46c7-89a7-437f2b972282)

The answer from qgis2web is this
![2024-07-17 08_15_59-Window](https://github.com/user-attachments/assets/b87de0c7-4532-4dd8-bf2e-8bc2f154ef26)

**Comment by tomchadwin** [comment]
You didn't use a graduated style, but a categorized one. Categorized styles have to match their values precisely, which is why @andreaordonselli's fix works. You could also use a graduated symbology, which would work even with the very precise values your layer contains.

**Comment by LuBa95** [comment]
Thank you so much!

**Comment by andreaordonselli** [comment]
Please consider donating a virtual coffee via the button on the home page to support the development of qgis2web.
Thank you.

**Comment by andreaordonselli** [comment]
I have just released version [3.23.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.23.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
