### ISSUE TITLE
Change default output to Leaflet

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#497]
I've thought about this a lot. I'd like to change the default to Leaflet for the following reasons:

1. Boundless's Web App Builder is an alternative for OL maps (https://github.com/boundlessgeo/qgis-webappbuilder-plugin), but there is no alternative for Leaflet
2. Leaflet library size is smaller
3. Leaflet code is simpler
4. I know Leaflet better
5. Under many circumstances, Leaflet outperforms OL

Does anyone have any counterarguments?

**Comment by joooeey** [comment]
Support!

I started using qgis2web a few months ago. I started with OL because it was the default but soon found out that Leaflet is better. Not sure what exactly was better about it. I think more functions and smaller output folder size. I also just tried exporting my project to OL and noticed that the popups for geometrically complicated GEOJson objects take forever to load.
