### ISSUE TITLE
Interactive legend and Map Title OL

### ISSUE THREAD

**Issue by fgillen01** [qgis2web/qgis2web#498]
Hi Tom,

Is there any possibility of adding in an Interactive legend and Map Title like the ones in Leaflet to the OpenLayers web map? If this is not in the plan could you point me in the direction of how I could add them myself.

Regards
Finbar

**Comment by OlaKov** [comment]
Hi Finbar,

I was able to add symbols to the layer switcher, something like this:
![image](https://user-images.githubusercontent.com/28122345/26885106-e30c4b46-4b5e-11e7-880a-9df976477f2e.png)

Please note that I had to draw my own symbols (in this case I quickly used Paint, but they would look much nicer if done in Illustrator). If you're interested in this type of solution please let me know.

In regards to the title, I don't know how Leaflet does this, but you can probably just add a `<div>` to the index.html:
```
<body>
        <div id="map">
        	<div id="title" style="position:absolute; left: 50%; z-index: 99">
        		<p>This is the title of my map</p>
        	</div>
```
you can style it further using the `#title` tag.


Regards,
Ola

**Comment by tomchadwin** [comment]
@OlaKov How did you get the symbols into the layer switcher? The Leaflet version gets the symbols out of QGIS, so these could be inserted into the legend, which would be great.

**Comment by OlaKov** [comment]
I drew my own tiny symbols, put them in a folder called graphics. Then within the ol3-layerswitcher.js, `ol.control.LayerSwitcher.prototype.renderLayer_ = function(lyr, idx) {` , added an array of my paths:

`var lyrLogos = ['<img src="graphics\/study_site_dot.jpg">','<img src="graphics\/canada_cities_dot.jpg">','<img src="graphics\/USA_cities_dot.jpg">','<img src="graphics\/canada_pol.jpg">','<img src="graphics\/USA_pol.jpg">'];`

I think originally the code was:

`var lyrTitle = lyr.get('title');`

But, I just added:

`var lyrTitle = lyrLogos[idx] + '&nbsp' + lyr.get('title');`

The index was already passed so it was quite easy. 

There is an interesting ol.Feature.GetStyle() method that can provide us with the style that was initially set for the features (like in the style.js that we are dealing with in the clusters), but this is feature specific, while the layer switcher is dealing with layers. I haven't looked into this too much yet..

**Comment by tomchadwin** [comment]
But this could be fantastic - all of that sounds doable automatically as part of the export process. Initially it would only be good for single symbol renders, but I wonder if there's even a chink of light for categorized.

I only wonder if there is a way of abstracting the code out of ol3-layerswitcher.js, so that we can safely update that in the future if @walkermatt releases a new version. Otherwise we would have to repatch it with your code each time there was a layerswitcher update.

**Comment by tomchadwin** [comment]
OK, I'd like to look at this properly, but it's probably not what you want to put instance data in the prototype. How about the following:

```javascript
var lyrTitle = lyr.get('title');
var lyrIcon = lyr.get('icon');
lyrTitle = lyrIcon + " " + lyrTitle;
```

Then add the `icon` property to your layer definition.

Better?

**Comment by tomchadwin** [comment]
Thanks to the suggestions by @OlaKov, icons are now present in the layers list in OL exports. The layout is a little rough, but if anyone is able to test, that would be great.

**Comment by tomchadwin** [comment]
Released as 2.20.0 and pushed to QGIS plugins repo.

**Comment by OlaKov** [comment]
Wow, that looks great. The only issue I'm seeing is with categorized and graduated layers, console error in the layers.js due to:

![image](https://user-images.githubusercontent.com/28122345/27309083-57acb166-550f-11e7-8212-d43c67a9ea96.png)

**Comment by tomchadwin** [comment]
Interesting. I wonder if it's because I used single quotes (because of the doubles in the HTML)? I'll try double quotes, and escape the internal quotes. Thanks for testing.

**Comment by walkermatt** [comment]
@tomchadwin glad you found a solution for this. I think the issue with categorized and graduated layers is that you need either to put the string all on one line or add a backslash at the end of each line (see https://davidwalsh.name/multiline-javascript-strings)

**Comment by tomchadwin** [comment]
Actually, I've got no JS error in the console. Not for graduated, at least. Is Chrome more tolerant - are you using a different browser?

**Comment by tomchadwin** [comment]
@walkermatt Thanks! I'll add the backslashes.

**Comment by tomchadwin** [comment]
Ah, my string is all on one line already:

'''javascript
jsonSource_lakes0.addFeatures(features_lakes0);var lyr_lakes0 = new ol.layer.Vector({
                source:jsonSource_lakes0, 
                style: style_lakes0,
                title: 'lakes<br /><img src="styles/legend/lakes0_0.png" />  20.0570 - 219.6906 <br /><img src="styles/legend/lakes0_1.png" />  219.6906 - 419.3242 <br /><img src="styles/legend/lakes0_2.png" />  419.3242 - 618.9578 <br /><img src="styles/legend/lakes0_3.png" />  618.9578 - 818.5914 <br /><img src="styles/legend/lakes0_4.png" />  818.5914 - 1018.2250 <br />'
            });
'''

I wonder why yours isn't, @OlaKov.

**Comment by OlaKov** [comment]
@tomchadwin That's quite weird, I created a new project, imported the shapefile (from qgis2web test folder) and I'm still getting the same issue. For graduated/categorized layers the QGIS preview window is blank and it doesn't work in the browser (blank), but once I edit layers.js, so that the string is one line (the way you have it), it works perfectly.. I'm using Chrome and QGIS 2.18.5 .. I'm looking at the python code and I don't understand what's making it jump to the next line..

**Comment by tomchadwin** [comment]
OK, I've got the same error as you now. No idea what happened there - wasn't looking at current master. Apologies. Fixing now.

**Comment by tomchadwin** [comment]
Right, possible fix committed. Can you test?

**Comment by tomchadwin** [comment]
Ah, fantastic. Thanks so much for testing.

**Comment by tomchadwin** [comment]
Released as 2.21.0 and pushed to QGIS plugins repo. Title still to do.

**Comment by fgillen01** [comment]
Great job @OlaKov and @tomchadwin !!! Only back in work after a lay off. OpenLayers working great!

**Comment by tomchadwin** [comment]
Hopefully another improvement coming soon: https://github.com/walkermatt/ol3-layerswitcher/pull/60

**Comment by tomchadwin** [comment]
For the title, @OlaKov's approach above sounds right, or the`div` could be added by script. The only gotcha is avoiding overlap with other map controls. I've already had to do some slightly hacky code for that before to fix https://github.com/tomchadwin/qgis2web/issues/391.

**Comment by fgillen01** [comment]
Tom, another addition I was thinking for qgis2web was the option of an info box on the left hand side which could give the user a description of the layers on the map/type of analysis/findings. Should I create  a new issue for this?

**Comment by tomchadwin** [comment]
@fgillen01 Isn't that just duplicating the functionality and content of the popups?

**Comment by usmanayyash** [comment]
Hi tomchadwin, 
i want to ask some questions about qgis2web ..
1. why update 2.27.1 qgis2web does not work for cluster and basemap in openlayers while version 2.26.0 works
2. why qgis2web polyline labeling does not work for (curved) can only display horizontal label
3. why search in openlayers and leaflets in qgis2web only supports one search, because we need more than one search such as name and number

how to solve it for my 3 questions .. please help

**Comment by tomchadwin** [comment]
@usmanayyash 

1. You're right - it's not working. New issue opened: #547
2. Because the labelling doesn't support it - sorry
3. Again, the search plugin doesn't support it - see https://github.com/webgeodatavore/ol3-search-layer ("At the moment, it works with single layer and a column name")

By the way, please open new issues, rather than adding an issue to an unrelated one. Thanks.

**Comment by ordisabeba** [comment]
It's a way to add many title in layer list?
using qgis layer groups it is no longer possible to manage the popup and then they end up at the bottom of the layer list
