### ISSUE TITLE
Lines disappearing with highlight on hover

### ISSUE THREAD

**Issue by gHupf** [qgis2web/qgis2web#589]
Not sure if this is a qgis2web or a leaflet bug, but if I use "highlight on hover" in my leaflet map if 2 or more line features are above each other the lower one always disappears if I hover the upper one. I added the two line features I have the problem with and also the style for the lower feature. Way is on top, lines below.

[hover_testfiles.zip](https://github.com/tomchadwin/qgis2web/files/1547332/hover_testfiles.zip)

**Comment by tomchadwin** [comment]
The problem is with the following set-up:

- Leaflet export
- highlight on hover
- multiple symbol layers

I've not figured out a way to restore the style for *multiple* symbol layers on mouseout in Leaflet. See https://github.com/perliedman/leaflet-multi-style/issues/6.

For the moment, I can only suggest changing one of the three elements in the list above - use OpenLayers, don't highlight on hover, or only use a single symbol layer.

Sorry not to have a solution for you.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
