### ISSUE TITLE
use NPM packages to fill directory "qgis2web/js/"

### ISSUE THREAD

**Issue by stefanocudini** [qgis2web/qgis2web#688]
Hi @tomchadwin,

I propose to use npm as a system of management of javascript dependsze
this would have many advantages including the maintenance of the versions of each javascript library in an easier way

currently on copi manually all javascript files in the js directory right?

using npm all the management of dependencies results in maintaining an anti-file package.json and in the build phase you can use various tools to automate the chaining in a single javascript file.

**Comment by tomchadwin** [comment]
> management of javascript dependsze

This is currently a major unsolved problem here - I investigated Greenkeeper and recently saw Dependabot, but have not implemented anything

> I propose to use npm

I'm not a node user myself, so I will have to rely on your expertise. The most basic of basic questions: you are not proposing to introduce node as a dependency in distribution? Most QGIS users will not be node users. However, if you mean as part of the build process hooked into Github, then that sounds great.

> currently on copi manually all javascript files in the js directory right?

Right, which is why many are not on current versions.

There is currently no build process for qgis2web. The only process hooked into Github is Travis CI. I therefore don't know how much work your proposal will require, and whether it will involve any fundamental changes to the repo.

Interested to hear your thoughts - as I say, it's been an unsolved problem for ages, so progress would be incredibly welcome.
