### ISSUE TITLE
filterable attribute table 

### ISSUE THREAD

**Issue by viafili** [qgis2web/qgis2web#962]
Hello,
thank you for your very useful plugin. I have a suggestion for an enhancement of the plugin. I think that filterable attribute table would be a great addition in some cases. Is it possible to add subroutine which generates simple attribute table with filter function (3 files, table.html, table.js, table.css)?
I wish you all the best
viafili

**Comment by Leri13** [comment]
Hello everyone,

the qgis2web plugin is a really usefull plugin and it simplifies many things. So I asked myselfe why was the ticket closed without a comment? I think displaying an attribute table would be an important feature.
Just a simple table would be really useful. Is there any prospect of something like this being implemented?

Best regards

**Comment by andreaordonselli** [comment]
Sorry, I don't remember why I closed the issue without providing feedback.
Please note that I am working hard to balance the functionality between openlayers and leaflet, i.e. bringing both to the same level. So at the moment adding new features is not a priority, also keep in mind that I am dedicating a lot of time just to keep qgis2web working since it is QGIS itself that proceeds and discontinues calls, definitions etc...

A further consideration must be made: in qgis2web few things have been created by hand from scratch, mostly third-party libraries have been integrated for both openlayers and leaflet. In essence:
- or you provide code to implement
- or provide links to libraries

Try doing a search and linking if you find something online in open code, then I'll see if it's feasible to implement it, ok?
Remember: both for openlayers and leaflet.

Thank you for using qgis2web, please consider donating a virtual coffee via the button on the home page.
